### ISSUE TITLE
Wrong transform with @putout/plugin-for-of

### ISSUE THREAD

**Issue by sirenkovladd** [coderaiser/putout#196]
```js
import {
  parse,
  transform,
} from 'putout';
import { print } from '@putout/printer';
import forOf from '@putout/plugin-for-of';

const js = `
a.forEach(aa=>d.push(aa)),
b.forEach(bb=>d.push(bb))`;

const ast = parse(js, {
  printer: 'putout',
});

let raw = print(ast);
console.log(raw)

console.log('----------------------')

transform(ast, js, {plugins: [['for-of', forOf]]});

raw = print(ast);
console.log(raw)
```

```
❯ node tt.js
(a.forEach((aa) => d.push(aa)), b.forEach((bb) => d.push(bb)));

----------------------
function(_ret) {
    for (const bb of b)
        _ret = d.push(bb);
    
    return _ret;
}();
```

Missing code for `a.forEach(aa=>d.push(aa))`

related to https://github.com/putoutjs/minify/issues/7

**Comment by coderaiser** [comment]
Thanks! Just fixed 🎉 . Please re-install 🐊. Is it works for you?

**Comment by sirenkovladd** [comment]
Try with 
```js
const js = `a.forEach(aa=>d.push(aa));
b.forEach(bb=>d.push(bb)`;
```

I see error
```js
/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:21855
        var error = new SyntaxError();
                    ^

SyntaxError: Unexpected token, expected "," (2:24)
    at constructor (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:21855:21)
    at JSXParserMixin.raise (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:26109:29)
    at JSXParserMixin.unexpected (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:26145:28)
    at JSXParserMixin.expect (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:26664:40)
    at JSXParserMixin.parseCallExpressionArguments (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35967:30)
    at JSXParserMixin.parseCoverCallAndAsyncArrowHead (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35858:43)
    at JSXParserMixin.parseSubscript (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35787:33)
    at JSXParserMixin.parseSubscripts (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35757:33)
    at JSXParserMixin.parseExprSubscripts (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35745:29)
    at JSXParserMixin.parseUpdate (/private/var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.mzJn82bRbE/node_modules/@putout/babel/bundle/index.js:35721:33) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 2, column: 24, index: 51 },
  pos: 51
}
```

**Comment by sirenkovladd** [comment]
It's better now, but I don't see any transformation and the forEach still exists

```sh
❯ node tt.js
(a.forEach((aa) => d.push(aa)), b.forEach((bb) => d.push(bb)));

----------------------
(a.forEach((aa) => d.push(aa)), b.forEach((bb) => d.push(bb)));
```

**Comment by coderaiser** [comment]
What kind of transformation do you what here?

**Comment by sirenkovladd** [comment]
in my opinion, it should be the most appropriate
```js
(function() {
    for (const aa of a)
        d.push(aa);
}(),
function() {
    for (const bb of b)
        d.push(bb);
}())
```

can correct me if you think otherwise

**Comment by sirenkovladd** [comment]
not sure if this applies to this task but I'll write here first
for code 
```js
const js = `const z=a.forEach(aa=>d.push(aa))`;
```
result
```js
❯ node tt.js
const z = a.forEach((aa) => d.push(aa));

----------------------
const z;
```
I expect something like
```js
const z = function() {
    for (const bb of b)
        d.push(bb);
}())
```

**Comment by coderaiser** [comment]
[Just fixed](https://github.com/coderaiser/putout/releases/tag/v34.8.0) 🎉 . Please re-install 🐊. Is it works for you?

**Comment by sirenkovladd** [comment]
But it removes the loop and without minification it causes a push
and after that it doesn't do anything

**Comment by coderaiser** [comment]
Have you tried new version?

**Comment by sirenkovladd** [comment]
Oh yes, the version was not the last
now I have a row without changes
I just thought that plugin-for-of must strictly change to for-of

but if it is skipped for minification then it seems it should just use a more complex condition than just replacing or skipping it

**Comment by coderaiser** [comment]
Look, [@putout/plugin-for-of](https://github.com/coderaiser/putout/tree/master/packages/plugin-for-of#readme) used both in **Putout** linter and **Minify**, so when trapped on **SequenceExpression** it just skippes transformation, since we have [`@putout/plugin-extract-sequence-expression`](https://github.com/coderaiser/putout/tree/master/packages/plugin-extract-sequence-expressions#readme) which will do the thing first.

About your case:

```js
a.forEach(aa=>d.push(aa)),
b.forEach(bb=>d.push(bb))`;
```

Now with help of [`@putout/plugin-minify`](https://github.com/coderaiser/putout/tree/master/packages/plugin-minify#merge-loops) it will be transformed to:

```js
for (const aa of [...a, ...b]) {
    d.push(aa);
}
```

And then all whitespaces will be reduced.

> it seems it should just use a more complex condition than just replacing or skipping it

What do you suggest?

**Comment by sirenkovladd** [comment]
Thank you, I understand now, thanks for the solution

**Comment by sirenkovladd** [comment]
And could you update the `minify` version as well?

**Comment by coderaiser** [comment]
It is updated, just re-install it

**Comment by sirenkovladd** [comment]
I see that the last version was a month ago
https://www.npmjs.com/package/minify?activeTab=versions

**Comment by coderaiser** [comment]
I’m using semantic versioning, just tr-install `minify` and it will update all dependencies.
