### ISSUE TITLE
Local plugins

### ISSUE THREAD

**Issue by retorquere** [coderaiser/putout#62]
How can I use a plugin that is local to my code, and not published on npmjs? I tried

```
putout(source.code, { plugins: './trace' })
```

and

```
putout(source.code, { plugins: require('./trace') })
```

**Comment by coderaiser** [comment]
If `plugin` local to your code you can use:

```js
putout(source.code, {
    plugins: [
        ['trace', require('./trace')],
    ]
})
```

**Comment by retorquere** [comment]
I'm using this main:

```
const putout = require('putout')

const source = { code: 'function X() { console.log("me") }' }

console.log(putout(source.code, {
    plugins: [
        ['trace', require('./trace')],
    ]
}))
```

the contents of `trace.js` is [this](https://github.com/coderaiser/putout/issues/61#issuecomment-852238154)

but I'm getting

```
/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/merge-visitors.js:85
        const message = msg || plugin.report(path);
                                      ^

TypeError: plugin.report is not a function
    at push (/Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/merge-visitors.js:85:39)
    at /Users/emile/github/better-bibtex/node_modules/.pnpm/@putout+engine-runner@10.0.1/node_modules/@putout/engine-runner/lib/include.js:44:5
    at NodePath._call (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/context.js:110:16)
    at TraversalContext.visitMultiple (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/context.js:136:19)
    at Function.traverse.node (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/emile/github/better-bibtex/node_modules/.pnpm/@babel+traverse@7.14.2/node_modules/@babel/traverse/lib/path/context.js:97:18)
```

**Comment by coderaiser** [comment]
Yes, you should have `report` defined in your [plugin](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#includer):

```js
module.exports.report = () => 'Log events should be added';
```

So `putout` can show information about found place, when `fix` is `false`.

**Comment by retorquere** [comment]
That did the job! Thanks!
